### PR TITLE
Fixes #26: settings names scope

### LINKED ISSUE #26: Plugin settings names
Technically plugin settings scoped for the `config_plugins` table should be named `block_filescan/<settingname>` rather than just `filescan/<settingname>`.

### PR DESCRIPTION
**Pull request by azito122**

### CODE REVIEW

**Comment by azito122** [comment]
I also took the liberty of fixing up the whitespace in `settings.php`. That change is in a separate commit, so if you'd rather I leave it out, just say so and I'll remove it.

**Comment by aruethe2** [comment]
@azito122 this is a great help -- thanks for all your work on this project.  I was wondering if I should to configure the update script to update database changes?  Or if we just make a note and anyone who is upgrading can make the changes manually.

**Comment by azito122** [comment]
@aruethe2 I believe that ideally, the upgrade script would take care of the database changes.

**Comment by azito122** [comment]
Added the name updates to the upgrade script. IMPORTANT NOTE: I left the version number (`$oldversion < #` blank, so don't forget to fill it in when you integrate to master (with whatever version first includes the new settings names).

**Pull request merged**
